#!/usr/bin/env node
/**
 * Generates tiny base64 blur placeholders from the seed cover images and
 * writes them to src/lib/coverBlur.ts for next/image `placeholder="blur"`.
 *
 * Run: cd anielab-web && node scripts/gen-blur.mjs
 */
import sharp from 'sharp'
import { readdirSync } from 'fs'
import { writeFileSync } from 'fs'
import { join, extname, basename, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const IMAGES_DIR = join(__dirname, '..', '..', 'anielab-backend', 'scripts', 'seed-images')
const OUT = join(__dirname, '..', 'src', 'lib', 'coverBlur.ts')

const files = readdirSync(IMAGES_DIR).filter((f) => /\.(png|jpe?g|webp)$/i.test(f))

const entries = []
for (const file of files) {
  // Stable key = filename minus extension (matches the prefix stored in
  // cover_ipfs_cid, e.g. "seed/stellar-sakura-1786….webp" -> "stellar-sakura").
  const key = basename(file, extname(file))
  const buf = await sharp(join(IMAGES_DIR, file))
    .resize({ width: 12 })
    .png({ quality: 60 })
    .toBuffer()
  const dataUri = `data:image/png;base64,${buf.toString('base64')}`
  entries.push({ key, dataUri })
  console.log(`  ${key} -> ${buf.length} bytes`)
}

const body = [
  '// Auto-generated by scripts/gen-blur.mjs — tiny blur placeholders for covers.',
  '// Keyed by the cover name prefix (cover_ipfs_cid minus timestamp/extension).',
  'export const COVER_BLUR: Record<string, string> = {',
  ...entries.map(({ key, dataUri }) => `  '${key}': '${dataUri}',`),
  '}',
  '',
  '// Neutral fallback so cards always get a soft placeholder.',
  "export const FALLBACK_BLUR =",
  "  'data:image/svg+xml;base64,' +",
  `  '${Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="9"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#292524"/><stop offset="1" stop-color="#451a03"/></linearGradient></defs><rect width="16" height="9" fill="url(#g)"/></svg>`
  ).toString('base64')}'`,
  '',
  '// Derive the blur data URI for a stored cover key.',
  'export function blurFor(coverKey: string | null | undefined): string {',
  "  if (!coverKey) return FALLBACK_BLUR",
  "  const name = coverKey.split('/').pop() ?? ''",
  "  const prefix = name.replace(/\\.\\w+$/, '').replace(/-\\d+$/, '')",
  '  return COVER_BLUR[prefix] ?? FALLBACK_BLUR',
  '}',
  '',
].join('\n')

writeFileSync(OUT, body)
console.log(`\nWrote ${entries.length} blur placeholders to ${OUT}`)
