/**
 * Typed bindings for the RevenueSplitter contract, generated by the Soroban
 * CLI and vendored from anielab-contracts/bindings/revenue-splitter.
 *
 * When the private npm package is published, replace this file with:
 *   export * from 'revenue-splitter'
 */
export * from '../../../vendor/revenue-splitter/dist/index.js'
